version: '3.5'

services:
  postgres:
    container_name: postgres_ff
    image: postgres:latest
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local